# Generated by Django 4.2.9 on 2024-01-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_delete_onetimepassword"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="nft_metadata",
        ),
    ]
